<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="DEMOQAtestSeleniumJ"
           tests="3"
           failures="1"
           errors="0"
           skipped="0"
           time="1,823">
    <properties></properties>

            <testcase
                name="TestPreventPropogationDragAndDrop1"
                time="0,671"
                classname="tests.TestDroppable">

            <failure type="java.lang.AssertionError" message="expected [Dropped! Inner droppable (not greedy)] but found [Outer droppable Inner droppable (not greedy)]">
                <![CDATA[java.lang.AssertionError: expected [Dropped! Inner droppable (not greedy)] but found [Outer droppable Inner droppable (not greedy)]
                org.testng.Assert.fail(Assert.java:97)org.testng.Assert.assertEqualsImpl(Assert.java:136)org.testng.Assert.assertEquals(Assert.java:118)org.testng.Assert.assertEquals(Assert.java:575)org.testng.Assert.assertEquals(Assert.java:585)tests.TestDroppable.TestPreventPropogationDragAndDrop1(TestDroppable.java:47)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)java.util.ArrayList.forEach(ArrayList.java:1259)org.testng.TestRunner.privateRun(TestRunner.java:770)org.testng.TestRunner.run(TestRunner.java:591)org.testng.SuiteRunner.runTest(SuiteRunner.java:402)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)org.testng.SuiteRunner.run(SuiteRunner.java:304)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)org.testng.TestNG.runSuitesLocally(TestNG.java:1102)org.testng.TestNG.runSuites(TestNG.java:1032)org.testng.TestNG.run(TestNG.java:1000)com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
            </failure>
    </testcase>


            <testcase
                name="TestSimpleDragAndDrop"
                time="0,528"
                classname="tests.TestDroppable">
            </testcase>
            <testcase
                name="TestPreventPropogationDragAndDrop2"
                time="0,624"
                classname="tests.TestDroppable">
            </testcase>
</testsuite>
